### ISSUE TITLE
monitoring callback function number is not passed in monitoring callback

### ISSUE THREAD

**Issue by hayashi770** [FairyDevicesRD/libmimixfe#4]
v1.0.3-rc2 pre-releaseにて
・addMonitoringCallback()の戻り値変更
・delMonitoringCallback()の追加
が行われ、キー情報としてid（モニタリングコールバック関数番号）が追加になりました。
addMonitoringCallback()では、呼び出し時に同一CallbackAddressを指定してもエラーにはならない旨の情報もいただいています。

xfeからcallbackされた際に上記id（モニタリングコールバック関数番号）を渡していただけるものと期待しておりましたが、インターフェースには追加されていないようです。
今後も追加のご予定はないのでしょうか？

--XFERecorder.hの関数定義--
int addMonitoringCallback(monitoringCallback_t callback, MonitoringAudioType type, AudioCodec codec, void* userdata);

int delMonitoringCallback(int id);

--XFETypedef.hのcallback関数定義--
using monitoringCallback_t = void (*)(const short* buffer,size_t buflen,void* userdata);

**Comment by nagisasaka** [comment]
ご質問いただきありがとうございます。

まず、前提として、`addMonitoringCallback()` では、`XFERecorder` インスタンスに対してモニタリングコールバックを追加できます。モニタリングコールバックとは、libmimixfe で録音した 18 ch（16 ch）音声を「モニター」するためのコールバック関数です。 ここで、モニターしたい音声として、18 ch / 48kHz 音声をそのまま欲しいのか、ダウンサンプリングした上で欲しいのか、さらにミックスダウンした上で欲しいのか、など、アプリケーション上の要望が異なるため、モニタリングしたい音声に対して、最小限のリアルタイム加工を施すことが可能です。また、それらの加工処理は、元となった 18ch / 48kHz 音声さえ取得できれば、ユーザープログラム側で実施することも当然に可能ですが、その加工処理は、エッジデバイスの限られた計算資源を考慮すると実装上簡単ではない場合があるため、XFE のユーティリティ機能として、そういった基本的な加工処理もサポートしているという位置付けとなります。

次に、そのような加工処理について、ユーザープログラム側（応用アプリケーション側）の都合で、複数の異なる加工種類の音声を同時に欲しい場合があると想定しています。例えば、1ch / 48kHz 音声（高音質）と、16ch / 16 kHz 音声（低音質だが多チャンネル）の２種類の音声を同時に取得したい、というような要望であり、前者は、ユーザーに対するプレイバック用音声、後者はデータ処理のための音声としてそれぞれ保存したい、というような場合です。このため、`addMonitoringCallback()` 関数を用いて、複数の異なる加工種類を指定し、複数の異なるユーザー定義コールバック関数を `XFERecorder` インスタンスに追加できるということが設計上の要件となっています。

ここで、今回のご質問についてですが、まず、libmimixfe は `addMonitoringCallback()` 関数で追加されるユーザー定義コールバック関数へのポインタについて、同一の関数ポインタが複数登録されることを妨げません。この理由は、妨げる必要性が無い（むしろ妨げるべきではない）と考えられるからです。

次に、複数回の `addMonitoringCallback()` 関数呼び出しにおいて、設計想定は、上述の通り、異なる関数ポインタが指定されるということですが、同一の関数ポインタが指定された場合、それらが libmimixfe から呼び出されたとき、その呼び出しは「基本的には」区別されません。「基本的には」と注釈したのは、ユーザープログラム側で区別することは可能であるからで、そのために `addMonitoringCallback()` 関数の第 4 引数である `void* userdata` を利用することができます。つまり、`addMonitoringCallback()` 関数を呼び出す際に、`userdata*` に例えば `std::string name = "myfunc1"` など任意のデータを与えて呼び出します。`userdata*` は、記載いただいた関数定義の通り、ユーザー定義コールバック関数が呼び出される際にも与えられるため、ユーザー定義コールバック関数内で `name` の値を条件とした if-else 分岐を書くことによって、 各回の呼び出しを区別することができます。このような実装により、複数回の `addMonitoringCallback()` 関数呼び出しに対して、同一の関数ポインタを指定することは可能であり、このような if-else 分岐に依るユーザープログラム側の実装を拒絶する理由はなく、これを API として妨げるべきではないと考えられます。

次に、ご指摘いただいた、モニタリングコールバック関数番号が、ユーザー定義コールバック関数が呼び出される際に与えられないということについては、与える必要がない（与えたとしても、それをユーザープログラム側で利用する目的が実質的にない）と考えられるため、冗長な引数であるという理由で、現時点では追加される予定はございません。

この点について補足します。 `addMonitoringCallback()` 関数から返されるモニタリングコールバック関数番号は、ユーザー定義コールバック関数を区別するために、 `XFERecorder` インスタンス内でユニークであることのみ保証されています。すなわち、その実際の値は、`addMonitoringCallback()` 関数を呼び出すまで分かりません。このため、例えば、上述した、`XFERecorder` による各回のユーザー定義コールバック関数呼び出しを区別するためにモニタリングコールバック関数番号を用いようと思ったとき、`addMonitoringCallback()` 関数の返り値として取得されたモニタリングコールバック関数番号の値を条件として用いてユーザー定義関数内の if-else 分岐（の右辺）を書かなければならないため、その値を受け渡すために、結局は `void* userdata` を使わなければなりません。これは上述したような、何らかの任意の値を使って区別することと変わりません。他の実装案としては、スレッドセーフなグローバル変数を使うという方法もありますが、スレッドローカルな変数が使えることを考えると、スレッドを跨ぐグローバル変数を用いる合理性は小さいと考えられます。また、他の理由によって、モニタリングコールバック関数番号を、ユーザー定義コールバック関数内で利用したい場合というものは、現行設計では想定されておりません。このため、現行想定の範囲内におきまして、モニタリングコールバック関数番号は、ユーザー定義コールバック関数が呼び出される際には与えられないという仕様となっております。

現行設計想定外となるようなユースケースがございましたら、今後の設計改善の参考とさせていただきたく、ご教示をいただければ幸いです。ご質問いただきありがとうございました。

**Comment by hayashi770** [comment]
ご回答いただきありがとうございました。

C,C++以外の言語でのxfeの利用をサポートするためにwrapper（御社ご提供のsample(ex2)をベースに作成したため、wrapperというよりは音声認識ライブラリと呼ぶほうがふさわしい実装にはなっています）を作成しています。

前バージョンの仕様上、 `addMonitoringCallback()` では、モニタリングコールバック関数番号および、 `delMonitoringCallback()` が存在しなかったため、モニタリングに関しては、wrapperとしては、１つのモニタリングしか許容していませんでした。

今回のバージョンで、複数個のモニタリングを扱えるようになったため、その機能もwrapperのユーザに提供しようと考えております。

示唆いただいた、「モニタリングコールバック関数番号を  `userdata`  で管理する方式」も考えましたが、すでにwrapperユーザがモニタリングを使用している現状、 `userdata`  をwrapperユーザ独自の目的で利用している可能性もあります。
そこで、少なからず今回の機能追加によりwrapperユーザプログラムへの改変の必要性は発生するとはいえ、その影響を最小限にとどめようと考え（つまり、wrapperの中で吸収しようとする目的のため）前述の質問をさせていただきました。

しかしながら、wrapperユーザに新規パラメタとしてモニタリングコールバック関数番号を管理させるような設計を行うのも、すでに使用している（またはしていない） `userdata` に変更を加える設計を行うのもユーザへのプログラム改修にかかる負荷に大きな違いはないという考えに至りました。

従いまして、ご示唆の通り、モニタリングコールバック関数番号につきましては `userdata` にて管理する方式を採用することとし、本questitonはクローズさせていただきます。
